import type { Metadata } from "next";

import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/AppSidebar";
import { ThemeProvider } from "./_components/ThemeProvider";
import { ModeToggle } from "./_components/ModeToggle";
import { Button } from "@/components/ui/button";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col dark:bg-[#0d1225]">
        <SidebarProvider>
          <TooltipProvider>
            <AppSidebar />
            <main className="w-full">
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <section className="flex items-center justify-between shadow w-full p-3">
                  <SidebarTrigger />
                  <main className="flex items-center space-x-4">
                    <ModeToggle />
                    <Button className="dark:bg-indigo-600 dark:text-white">
                      Sign Up
                    </Button>
                  </main>
                </section>
                {children}
              </ThemeProvider>
            </main>
          </TooltipProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
